-- Original ScholarEdge question expansion pack.
-- These questions are newly written for ScholarEdge. The source_reference field
-- records public format guidance only; no official, paid, or third-party
-- questions have been copied or closely paraphrased.

insert into public.questions (
  legacy_id,
  content,
  options,
  correct_option_id,
  explanation,
  difficulty,
  subject,
  exam_type,
  year_level,
  topic,
  subtopic,
  skill_tags,
  source_reference,
  time_limit_seconds,
  status,
  approved_at
) values
(
  'se-20260629-naplan-num-y5-001',
  $$A school garden has 6 equal rows of seedlings. Each row has 14 seedlings. After planting, 9 seedlings are moved to another bed. How many seedlings remain in the original garden?$$,
  '[{"id":"a","text":"75"},{"id":"b","text":"78"},{"id":"c","text":"84"},{"id":"d","text":"93"}]'::jsonb,
  'a',
  $$First find the total seedlings: 6 x 14 = 84. Then subtract the 9 seedlings moved away: 84 - 9 = 75.$$,
  2,
  'maths',
  'naplan',
  5,
  'Number and Algebra',
  'Multi-step operations',
  array['multiplication','subtraction','word problems'],
  'Format guidance: ACARA NAPLAN public demonstration site / NAPLAN numeracy domains',
  75,
  'approved',
  now()
),
(
  'se-20260629-naplan-read-y5-001',
  $$Read the passage:

"The creek looked shallow from the bridge, but when Noah stepped closer he saw the water moving quickly beneath the surface. Leaves spun in little circles before being dragged downstream."

What is the main warning suggested by the passage?$$,
  '[{"id":"a","text":"The creek is safe because it looks shallow."},{"id":"b","text":"The leaves are blocking the bridge."},{"id":"c","text":"The water may be more dangerous than it first appears."},{"id":"d","text":"Noah should collect the leaves before they float away."}]'::jsonb,
  'c',
  $$The passage contrasts how the creek looks from far away with clues that it is fast-moving. The spinning leaves and strong current suggest hidden danger.$$,
  3,
  'reading',
  'naplan',
  5,
  'Reading Comprehension',
  'Inference',
  array['inference','context clues','main idea'],
  'Format guidance: ACARA NAPLAN public demonstration site / reading domain',
  75,
  'approved',
  now()
),
(
  'se-20260629-naplan-conv-y7-001',
  $$Which sentence is punctuated correctly?$$,
  '[{"id":"a","text":"Before the bell rang, the class packed away their books."},{"id":"b","text":"Before, the bell rang the class packed away their books."},{"id":"c","text":"Before the bell rang the class, packed away their books."},{"id":"d","text":"Before the bell, rang the class packed away their books."}]'::jsonb,
  'a',
  $$When a sentence begins with a dependent clause, such as "Before the bell rang", a comma is used before the main clause.$$,
  3,
  'conventions',
  'naplan',
  7,
  'Language Conventions',
  'Commas after introductory clauses',
  array['punctuation','commas','sentence structure'],
  'Format guidance: ACARA NAPLAN public demonstration site / conventions domain',
  45,
  'approved',
  now()
),
(
  'se-20260629-naplan-write-y7-001',
  $$A student is writing a persuasive text about whether school canteens should sell only healthy food. Which opening is strongest?$$,
  '[{"id":"a","text":"This essay is about school canteens and food."},{"id":"b","text":"I think canteens should maybe sell better food."},{"id":"c","text":"Every lunch order is a chance to help students learn, focus and build healthy habits."},{"id":"d","text":"Some schools have canteens and some food is unhealthy."}]'::jsonb,
  'c',
  $$Option C is clear, persuasive and purposeful. It presents the issue as important and gives reasons the reader can expect the text to develop.$$,
  3,
  'writing',
  'naplan',
  7,
  'Writing',
  'Persuasive openings',
  array['persuasion','audience','opening sentence'],
  'Format guidance: ACARA NAPLAN public demonstration site / writing domain',
  60,
  'approved',
  now()
),
(
  'se-20260629-icas-sci-y6-001',
  $$A student tests which paper towel absorbs the most water. She uses the same volume of water, the same size towel piece and the same timing for each brand. Why is this a fair test?$$,
  '[{"id":"a","text":"Only one main variable is changed."},{"id":"b","text":"Every towel brand is tested in a different way."},{"id":"c","text":"The student already knows the answer."},{"id":"d","text":"The test does not need measurements."}]'::jsonb,
  'a',
  $$A fair test changes only the variable being investigated, in this case the towel brand. Keeping water volume, size and timing the same makes the comparison valid.$$,
  3,
  'science',
  'general',
  6,
  'Science Inquiry',
  'Fair testing',
  array['variables','fair test','scientific method'],
  'Format guidance: ICAS Science question/time table and science inquiry focus',
  60,
  'approved',
  now()
),
(
  'se-20260629-icas-sci-y8-001',
  $$A graph shows that as the temperature of a gas increases, its volume also increases when pressure is kept constant. Which conclusion is best supported?$$,
  '[{"id":"a","text":"Temperature has no effect on gas volume."},{"id":"b","text":"Gas particles move less when heated."},{"id":"c","text":"Heating the gas is linked with an increase in volume."},{"id":"d","text":"Pressure must also be increasing."}]'::jsonb,
  'c',
  $$The question states that pressure is kept constant and volume rises with temperature. The supported conclusion is that heating is linked with greater volume.$$,
  4,
  'science',
  'general',
  8,
  'Physical Sciences',
  'Interpreting relationships',
  array['data interpretation','variables','gas behaviour'],
  'Format guidance: ICAS Science question/time table and scientific reasoning focus',
  75,
  'approved',
  now()
),
(
  'se-20260629-icas-maths-y7-001',
  $$A number is doubled, then 7 is added. The result is 31. What was the original number?$$,
  '[{"id":"a","text":"12"},{"id":"b","text":"15"},{"id":"c","text":"19"},{"id":"d","text":"24"}]'::jsonb,
  'a',
  $$Work backwards: 31 - 7 = 24. If doubling gave 24, the original number was 24 / 2 = 12.$$,
  3,
  'maths',
  'general',
  7,
  'Algebra',
  'Working backwards',
  array['algebra','inverse operations','problem solving'],
  'Format guidance: ICAS Mathematics question/time table and problem-solving focus',
  60,
  'approved',
  now()
),
(
  'se-20260629-icas-eng-y8-001',
  $$Read the sentence:

"The mayor described the proposal as a bridge between tradition and innovation."

What does the metaphor suggest?$$,
  '[{"id":"a","text":"The proposal is about building a real bridge."},{"id":"b","text":"The proposal connects older values with new ideas."},{"id":"c","text":"The proposal rejects all traditional ideas."},{"id":"d","text":"The mayor prefers engineering to planning."}]'::jsonb,
  'b',
  $$A bridge connects two places. Here, the metaphor suggests the proposal connects tradition with innovation.$$,
  4,
  'reading',
  'general',
  8,
  'Reading Comprehension',
  'Figurative language',
  array['metaphor','interpretation','vocabulary'],
  'Format guidance: ICAS English question/time table and higher-order reading focus',
  60,
  'approved',
  now()
),
(
  'se-20260629-icas-write-y6-001',
  $$A student is planning a short imaginative story. Which plan is most likely to create a clear narrative?$$,
  '[{"id":"a","text":"List ten unrelated funny events."},{"id":"b","text":"Begin with a problem, build tension, then show how the character responds."},{"id":"c","text":"Describe the setting only and avoid characters."},{"id":"d","text":"Write the ending first and leave out the middle."}]'::jsonb,
  'b',
  $$A clear narrative usually has a problem, rising action and a response or resolution. This gives the story direction.$$,
  3,
  'writing',
  'general',
  6,
  'Writing',
  'Narrative planning',
  array['narrative','structure','planning'],
  'Format guidance: ICAS Writing paper table and writing task focus',
  60,
  'approved',
  now()
),
(
  'se-20260629-nsw-select-read-y6-001',
  $$Read the passage:

"Talia had rehearsed her speech so often that the first three lines appeared in her mind like words on a screen. Yet when she saw the crowded hall, she folded the cue cards until their corners bent."

What is Talia most likely feeling?$$,
  '[{"id":"a","text":"Prepared but nervous"},{"id":"b","text":"Bored and careless"},{"id":"c","text":"Angry with the audience"},{"id":"d","text":"Confused about her topic"}]'::jsonb,
  'a',
  $$Talia knows her speech well, which shows preparation. Folding the cue cards when she sees the crowd suggests nervousness.$$,
  4,
  'reading',
  'selective',
  6,
  'Selective Reading',
  'Character inference',
  array['inference','character','evidence'],
  'Format guidance: NSW Department of Education selective high school practice tests page',
  75,
  'approved',
  now()
),
(
  'se-20260629-nsw-select-math-y6-001',
  $$A code uses two numbers. The first number is multiplied by 3, then the second number is subtracted. If the code for (8, 5) is 19, what is the code for (11, 7)?$$,
  '[{"id":"a","text":"24"},{"id":"b","text":"26"},{"id":"c","text":"28"},{"id":"d","text":"40"}]'::jsonb,
  'b',
  $$The rule is 3 x first number - second number. For (11, 7): 3 x 11 - 7 = 33 - 7 = 26.$$,
  4,
  'maths',
  'selective',
  6,
  'Mathematical Reasoning',
  'Rule application',
  array['patterns','operations','reasoning'],
  'Format guidance: NSW Department of Education selective high school mathematical reasoning information',
  75,
  'approved',
  now()
),
(
  'se-20260629-nsw-select-think-y6-001',
  $$All glims are norps. Some norps are velts. Which statement must be true?$$,
  '[{"id":"a","text":"All glims are velts."},{"id":"b","text":"Some velts are glims."},{"id":"c","text":"All glims are norps."},{"id":"d","text":"No norps are glims."}]'::jsonb,
  'c',
  $$The first sentence directly states that all glims are norps. The information about some norps being velts does not prove anything about glims and velts.$$,
  5,
  'reasoning',
  'selective',
  6,
  'Thinking Skills',
  'Deductive reasoning',
  array['logic','deduction','must be true'],
  'Format guidance: NSW Department of Education selective high school thinking skills information',
  60,
  'approved',
  now()
),
(
  'se-20260629-vic-sehs-qr-y8-001',
  $$The sequence 4, 9, 19, 39, 79 follows a rule. What is the next term?$$,
  '[{"id":"a","text":"119"},{"id":"b","text":"149"},{"id":"c","text":"159"},{"id":"d","text":"169"}]'::jsonb,
  'c',
  $$Each term is doubled and then 1 is added: 4 x 2 + 1 = 9, 9 x 2 + 1 = 19, and so on. The next term is 79 x 2 + 1 = 159.$$,
  5,
  'reasoning',
  'selective',
  8,
  'Quantitative Reasoning',
  'Number patterns',
  array['patterns','quantitative reasoning','sequences'],
  'Format guidance: ACER Victorian Selective Entry High Schools exam format',
  60,
  'approved',
  now()
),
(
  'se-20260629-vic-sehs-verbal-y8-001',
  $$Complete the analogy:

Blueprint is to building as outline is to ____.$$,
  '[{"id":"a","text":"essay"},{"id":"b","text":"window"},{"id":"c","text":"hammer"},{"id":"d","text":"paint"}]'::jsonb,
  'a',
  $$A blueprint is a plan for a building. An outline is a plan for an essay or written response.$$,
  4,
  'reasoning',
  'selective',
  8,
  'Verbal Reasoning',
  'Analogies',
  array['analogy','word relationships','verbal reasoning'],
  'Format guidance: ACER Victorian Selective Entry High Schools verbal reasoning focus',
  45,
  'approved',
  now()
),
(
  'se-20260629-vic-sehs-write-y8-001',
  $$A student must write a precise response about whether technology improves learning. Which thesis is strongest?$$,
  '[{"id":"a","text":"Technology is a thing lots of people use at school."},{"id":"b","text":"I will discuss technology and learning in this response."},{"id":"c","text":"When used with clear goals, technology improves learning by giving students faster feedback and broader access to information."},{"id":"d","text":"Technology is always good and schools should use it all the time."}]'::jsonb,
  'c',
  $$Option C gives a clear position and two specific reasons. It is precise and balanced, unlike the vague or exaggerated alternatives.$$,
  4,
  'writing',
  'selective',
  8,
  'Writing',
  'Thesis statements',
  array['writing','argument','precision'],
  'Format guidance: ACER Victorian Selective Entry High Schools writing task focus',
  75,
  'approved',
  now()
),
(
  'se-20260629-acer-humanities-y8-001',
  $$A museum label says:

"The painting shows a busy port at sunset. Traders unload crates while passengers wait beside a steamship. The scene suggests a town shaped by movement, trade and migration."

Which idea is best supported by the source?$$,
  '[{"id":"a","text":"The town was isolated from other places."},{"id":"b","text":"The port helped connect people and goods."},{"id":"c","text":"The steamship was used only for fishing."},{"id":"d","text":"The painting shows a farming community."}]'::jsonb,
  'b',
  $$The source mentions traders, crates, passengers and a steamship. These details support the idea that the port connected people and goods.$$,
  4,
  'reading',
  'scholarship',
  8,
  'Humanities',
  'Source interpretation',
  array['source analysis','inference','humanities'],
  'Format guidance: ACER Scholarship Tests humanities-style source interpretation',
  75,
  'approved',
  now()
),
(
  'se-20260629-acer-maths-y8-001',
  $$A rectangle has a perimeter of 54 cm. Its length is twice its width plus 3 cm. What is the width?$$,
  '[{"id":"a","text":"6 cm"},{"id":"b","text":"8 cm"},{"id":"c","text":"9 cm"},{"id":"d","text":"12 cm"}]'::jsonb,
  'b',
  $$Let the width be w. The length is 2w + 3. Perimeter is 2(length + width), so 2(2w + 3 + w) = 54. This gives 6w + 6 = 54, so w = 8.$$,
  5,
  'maths',
  'scholarship',
  8,
  'Mathematics',
  'Algebraic geometry',
  array['algebra','perimeter','problem solving'],
  'Format guidance: ACER Scholarship Tests mathematics and reasoning focus',
  90,
  'approved',
  now()
),
(
  'se-20260629-edutest-verbal-y7-001',
  $$Choose the pair that has the same relationship as:

thermometer : temperature$$,
  '[{"id":"a","text":"compass : direction"},{"id":"b","text":"clock : furniture"},{"id":"c","text":"map : weather"},{"id":"d","text":"ruler : colour"}]'::jsonb,
  'a',
  $$A thermometer measures temperature. A compass indicates direction. The other pairs do not show the same tool-to-measure relationship.$$,
  4,
  'reasoning',
  'scholarship',
  7,
  'Verbal Reasoning',
  'Analogies',
  array['verbal reasoning','analogy','relationships'],
  'Format guidance: EduTest practice test information for verbal reasoning',
  45,
  'approved',
  now()
),
(
  'se-20260629-edutest-num-y7-001',
  $$Find the missing number:

3, 8, 18, 38, __$$,
  '[{"id":"a","text":"58"},{"id":"b","text":"68"},{"id":"c","text":"78"},{"id":"d","text":"88"}]'::jsonb,
  'c',
  $$The pattern is multiply by 2 and add 2: 3 x 2 + 2 = 8, 8 x 2 + 2 = 18, 18 x 2 + 2 = 38. Next: 38 x 2 + 2 = 78.$$,
  4,
  'maths',
  'scholarship',
  7,
  'Numerical Reasoning',
  'Number sequences',
  array['numerical reasoning','patterns','sequences'],
  'Format guidance: EduTest practice test information for numerical reasoning',
  45,
  'approved',
  now()
),
(
  'se-20260629-edutest-read-y7-001',
  $$Read the passage:

"The new library was not the largest building in town, but it became the busiest. Students came for quiet corners, retirees came for newspapers, and local artists came to display their work."

What is the main idea?$$,
  '[{"id":"a","text":"The library is mainly for artists."},{"id":"b","text":"The library has become an important shared community space."},{"id":"c","text":"The library is too small for the town."},{"id":"d","text":"Most people visit the library only to read newspapers."}]'::jsonb,
  'b',
  $$The passage lists different groups using the library for different purposes. This supports the idea that it is a shared community space.$$,
  3,
  'reading',
  'scholarship',
  7,
  'Reading Comprehension',
  'Main idea',
  array['main idea','community','inference'],
  'Format guidance: EduTest practice test information for reading comprehension',
  75,
  'approved',
  now()
),
(
  'se-20260629-edutest-math-y8-001',
  $$A cyclist travels 18 km in 45 minutes. If she keeps the same average speed, how far will she travel in 2 hours?$$,
  '[{"id":"a","text":"36 km"},{"id":"b","text":"42 km"},{"id":"c","text":"48 km"},{"id":"d","text":"54 km"}]'::jsonb,
  'c',
  $$45 minutes is three quarters of an hour. A distance of 18 km in 0.75 hours means 24 km per hour. In 2 hours she travels 48 km.$$,
  4,
  'maths',
  'scholarship',
  8,
  'Mathematics',
  'Rates',
  array['rates','proportional reasoning','distance'],
  'Format guidance: EduTest practice test information for mathematics achievement',
  90,
  'approved',
  now()
),
(
  'se-20260629-hsc-english-read-y11-001',
  $$Read the sentence:

"The photograph does not simply preserve the past; it asks the viewer to question who has been left outside the frame."

What is the best interpretation?$$,
  '[{"id":"a","text":"The photograph is technically unclear."},{"id":"b","text":"The photograph encourages reflection on memory and exclusion."},{"id":"c","text":"The photographer forgot to include the main subject."},{"id":"d","text":"The viewer should ignore the historical context."}]'::jsonb,
  'b',
  $$The sentence suggests that the image preserves memory but also raises questions about absence and exclusion. This is a conceptual interpretation.$$,
  5,
  'reading',
  'general',
  11,
  'HSC English Skills',
  'Unseen text interpretation',
  array['human experiences','interpretation','unseen text'],
  'Format guidance: NESA English Standard HSC exam packs and resources',
  90,
  'approved',
  now()
),
(
  'se-20260629-hsc-english-write-y12-001',
  $$Which topic sentence best suits an analytical paragraph about how a composer represents resilience?$$,
  '[{"id":"a","text":"Resilience is something many people have in hard times."},{"id":"b","text":"This paragraph is about the composer and resilience."},{"id":"c","text":"Through recurring storm imagery, the composer presents resilience as a process of enduring pressure rather than avoiding it."},{"id":"d","text":"The text has many techniques that are interesting to readers."}]'::jsonb,
  'c',
  $$A strong analytical topic sentence names a technique or textual feature and links it to a clear idea. Option C does both.$$,
  5,
  'writing',
  'general',
  12,
  'HSC English Skills',
  'Analytical topic sentences',
  array['analysis','topic sentence','resilience'],
  'Format guidance: NESA English Standard HSC exam packs and marking resources',
  75,
  'approved',
  now()
),
(
  'se-20260629-vce-english-read-y11-001',
  $$In an argument analysis task, a writer describes a proposed stadium as "a concrete monster looming over our neighbourhood". What is the effect of this language?$$,
  '[{"id":"a","text":"It presents the stadium as harmless and useful."},{"id":"b","text":"It uses emotive imagery to make the stadium seem threatening."},{"id":"c","text":"It gives a neutral technical description of the building."},{"id":"d","text":"It proves that the stadium will be unsafe."}]'::jsonb,
  'b',
  $$The phrase "concrete monster" is emotive and metaphorical. It positions readers to view the stadium as threatening or unwelcome.$$,
  5,
  'reading',
  'general',
  11,
  'VCE English Skills',
  'Argument analysis',
  array['argument analysis','emotive language','metaphor'],
  'Format guidance: VCAA VCE English examination specifications and past examination resources',
  75,
  'approved',
  now()
),
(
  'se-20260629-vce-english-write-y12-001',
  $$A student is revising a text response essay. Which revision most improves analytical precision?$$,
  '[{"id":"a","text":"The author uses lots of techniques to show things."},{"id":"b","text":"The author makes the character sad in many scenes."},{"id":"c","text":"By narrowing the narration to the character''s private doubts, the author reveals how fear can distort moral judgement."},{"id":"d","text":"This quote is good because it supports my point."}]'::jsonb,
  'c',
  $$Option C identifies a technique, links it to a character experience and explains a broader idea. The other options are vague.$$,
  5,
  'writing',
  'general',
  12,
  'VCE English Skills',
  'Text response analysis',
  array['text response','analytical precision','revision'],
  'Format guidance: VCAA VCE English examination specifications and past examination resources',
  90,
  'approved',
  now()
),
(
  'se-20260629-general-sci-y7-001',
  $$A student notices that bread goes mouldy faster in a warm cupboard than in the refrigerator. Which question would lead to the best investigation?$$,
  '[{"id":"a","text":"Does temperature affect the rate of mould growth on bread?"},{"id":"b","text":"Why does bread taste better when toasted?"},{"id":"c","text":"Which brand of bread has the nicest packaging?"},{"id":"d","text":"Do students prefer white bread or wholemeal bread?"}]'::jsonb,
  'a',
  $$The observation compares mould growth in warm and cold conditions. A good investigation question focuses on the effect of temperature on mould growth.$$,
  3,
  'science',
  'general',
  7,
  'Science Inquiry',
  'Investigable questions',
  array['science inquiry','investigation','variables'],
  'Format guidance: ICAS Science and Australian Curriculum science inquiry skills',
  60,
  'approved',
  now()
)
on conflict (legacy_id) do nothing;
